services:
  - type: web
    name: employee-dashboard
    runtime: static
    rootDir: Website/Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_FILE_BASE_URL
        sync: false
      - key: VITE_LANDING_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: employer-dashboard
    runtime: static
    rootDir: Website/Employer-Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_LANDING_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: admin-dashboard
    runtime: static
    rootDir: Website/Company-Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_FILE_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: mzobs-landing
    runtime: static
    rootDir: Website/Landing-Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_EMPLOYEE_APP_URL
        sync: false
      - key: VITE_EMPLOYER_APP_URL
        sync: false
      - key: VITE_EMPLOYER_API_URL
        sync: false
      - key: VITE_EMPLOYEE_API_URL
        sync: false
      - key: VITE_CONTACT_API_URL
        sync: false
      - key: VITE_PUBLIC_JOBS_API_URL
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_MSG91_WIDGET_ID
        sync: false
      - key: VITE_MSG91_TOKEN_AUTH
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
