// AICTE-approved colleges (2025-26) for the "add campus" form's college
// picker. One JSON file per state in src/data/colleges/, generated by
// scripts/buildColleges.js from data/aicte-colleges-2025-26.md — each is a
// separate lazily loaded chunk, so the page only downloads the state chosen.
//
// The source list has only state + name; `type` is inferred from the name
// (see the script), so it narrows the list but isn't official data.

// Same order as the typeIndex values in the JSON files.
export const COLLEGE_TYPES = ['University', 'Engineering College', 'Degree College', 'Management Institute', 'Polytechnic', 'Other']

const loaders = import.meta.glob('../data/colleges/*.json')

const stateSlug = (state) => state.toLowerCase().replace(/[^a-z]+/g, '-').replace(/^-|-$/g, '')

const cache = new Map()

// → [{ name, type }] for the state, or [] when the list has none for it.
export function loadStateColleges(state) {
  if (!state) return Promise.resolve([])
  if (!cache.has(state)) {
    const load = loaders[`../data/colleges/${stateSlug(state)}.json`]
    const promise = load
      ? load().then((mod) => (mod.default ?? mod).map(([name, t]) => ({ name, type: COLLEGE_TYPES[t] ?? 'Other' })))
      : Promise.resolve([])
    // A failed load (e.g. offline) isn't cached, so it can be retried.
    cache.set(state, promise.catch((err) => (cache.delete(state), Promise.reject(err))))
  }
  return cache.get(state)
}
