// Talent Lens' candidate pool — the broader Mzobs talent database a recruiter
// searches (distinct from `/candidates`, which is only people who applied to
// THIS company's postings). There's no backend endpoint for that broader
// search yet, so this is a realistic mock dataset the rest of Talent Lens
// (parseQuery, matchEngine, trustSignal) runs against — swap this module's
// export for a real `GET /talent-lens/candidates` call later and everything
// downstream keeps working unchanged, since they all just consume `Candidate[]`.
// See types.js for the shape.

/** @type {import('./types').Candidate[]} */
export const TALENT_POOL = [
  {
    id: 'tl-1',
    name: 'Arjun Mehta',
    initials: 'AM',
    designation: 'Backend Developer',
    currentCompany: 'Finzo Payments',
    experienceYears: 3.5,
    currentSalaryLPA: 14,
    expectedSalaryLPA: 19,
    location: 'Bengaluru',
    preferredLocations: ['Bengaluru', 'Remote'],
    noticePeriodDays: 38,
    skills: ['Python', 'FastAPI', 'AWS', 'PostgreSQL', 'Docker', 'Redis'],
    industry: 'Fintech',
    employmentType: 'Full-time',
    companyType: 'Startup',
    workMode: 'Hybrid',
    education: [{ degree: 'B.Tech, Computer Science', institute: 'RV College of Engineering', year: 2020 }],
    workHistory: [
      { role: 'Backend Developer', company: 'Finzo Payments', startYear: 2022, endYear: null },
      { role: 'Software Engineer', company: 'Kavia Labs', startYear: 2020, endYear: 2022 },
    ],
    projects: [{ name: 'Ledger reconciliation service', description: 'Rebuilt a FastAPI + AWS batch pipeline that cut reconciliation time from 6 hours to 40 minutes.' }],
    resumeAvailable: true,
    hasPortfolio: true,
    portfolioLink: 'github.com/arjunmehta',
    lastActiveDaysAgo: 2,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: true, profileRecentlyUpdatedDays: 4 },
  },
  {
    id: 'tl-2',
    name: 'Sneha Kulkarni',
    initials: 'SK',
    designation: 'Python Developer',
    currentCompany: 'Orbital Health',
    experienceYears: 2.5,
    currentSalaryLPA: 11,
    expectedSalaryLPA: 16,
    location: 'Bengaluru',
    preferredLocations: ['Bengaluru', 'Pune'],
    noticePeriodDays: 22,
    skills: ['Python', 'FastAPI', 'AWS', 'MongoDB', 'CI/CD'],
    industry: 'Healthcare',
    employmentType: 'Full-time',
    companyType: 'Product',
    workMode: 'Remote',
    education: [{ degree: 'B.E, Information Science', institute: 'BMS College of Engineering', year: 2021 }],
    workHistory: [
      { role: 'Python Developer', company: 'Orbital Health', startYear: 2023, endYear: null },
      { role: 'Associate Engineer', company: 'Wells & Co', startYear: 2021, endYear: 2023 },
    ],
    projects: [{ name: 'Patient intake API', description: 'Built the FastAPI service handling patient intake for 40+ clinics on AWS Lambda.' }],
    resumeAvailable: true,
    hasPortfolio: false,
    portfolioLink: null,
    lastActiveDaysAgo: 1,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: false, profileRecentlyUpdatedDays: 1 },
  },
  {
    id: 'tl-3',
    name: 'Rohit Nair',
    initials: 'RN',
    designation: 'Software Engineer',
    currentCompany: 'Freelance',
    experienceYears: 4,
    currentSalaryLPA: 0,
    expectedSalaryLPA: 18,
    location: 'Kochi',
    preferredLocations: ['Bengaluru', 'Remote'],
    noticePeriodDays: 0,
    skills: ['Python', 'Django', 'AWS', 'Celery', 'PostgreSQL'],
    industry: 'Technology',
    employmentType: 'Full-time',
    companyType: 'Services',
    workMode: 'Remote',
    education: [{ degree: 'B.Tech, Computer Science', institute: 'NIT Calicut', year: 2019 }],
    workHistory: [
      { role: 'Freelance Backend Engineer', company: 'Self-employed', startYear: 2023, endYear: null },
      { role: 'Software Engineer', company: 'Digivance Systems', startYear: 2019, endYear: 2023 },
    ],
    projects: [{ name: 'Multi-tenant billing engine', description: 'Django + Celery billing engine handling recurring charges for 12 SaaS clients.' }],
    resumeAvailable: true,
    hasPortfolio: true,
    portfolioLink: 'rohitnair.dev',
    lastActiveDaysAgo: 5,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: false, employmentVerified: false, profileRecentlyUpdatedDays: 12 },
  },
  {
    id: 'tl-4',
    name: 'Priya Raghavan',
    initials: 'PR',
    designation: 'Senior React Developer',
    currentCompany: 'Loop Commerce',
    experienceYears: 4.5,
    currentSalaryLPA: 18,
    expectedSalaryLPA: 24,
    location: 'Bengaluru',
    preferredLocations: ['Bengaluru'],
    noticePeriodDays: 18,
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'Tailwind CSS'],
    industry: 'E-commerce',
    employmentType: 'Full-time',
    companyType: 'Product',
    workMode: 'Hybrid',
    education: [{ degree: 'B.E, Computer Science', institute: 'PES University', year: 2019 }],
    workHistory: [
      { role: 'Senior React Developer', company: 'Loop Commerce', startYear: 2022, endYear: null },
      { role: 'Frontend Developer', company: 'Bright Retail', startYear: 2019, endYear: 2022 },
    ],
    projects: [{ name: 'Checkout redesign', description: 'Led the React/Next.js rebuild of checkout, improving conversion by 9%.' }],
    resumeAvailable: true,
    hasPortfolio: true,
    portfolioLink: 'priyaraghavan.design',
    lastActiveDaysAgo: 3,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: true, profileRecentlyUpdatedDays: 6 },
  },
  {
    id: 'tl-5',
    name: 'Karthik Subramaniam',
    initials: 'KS',
    designation: 'Data Analyst',
    currentCompany: 'Vantage Retail',
    experienceYears: 2,
    currentSalaryLPA: 9,
    expectedSalaryLPA: 13,
    location: 'Chennai',
    preferredLocations: ['Chennai', 'Bengaluru', 'Remote'],
    noticePeriodDays: 30,
    skills: ['SQL', 'Python', 'Power BI', 'Excel', 'A/B testing'],
    industry: 'Retail',
    employmentType: 'Full-time',
    companyType: 'MNC',
    workMode: 'On-site',
    education: [{ degree: 'B.Sc, Statistics', institute: 'Loyola College', year: 2022 }],
    workHistory: [{ role: 'Data Analyst', company: 'Vantage Retail', startYear: 2022, endYear: null }],
    projects: [{ name: 'Inventory forecasting dashboard', description: 'Power BI dashboard that reduced stockouts by 14% across 60 stores.' }],
    resumeAvailable: true,
    hasPortfolio: false,
    portfolioLink: null,
    lastActiveDaysAgo: 9,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: false, profileRecentlyUpdatedDays: 20 },
  },
  {
    id: 'tl-6',
    name: 'Ananya Iyer',
    initials: 'AI',
    designation: 'Product Designer',
    currentCompany: 'Formless Studio',
    experienceYears: 3,
    currentSalaryLPA: 13,
    expectedSalaryLPA: 17,
    location: 'Bengaluru',
    preferredLocations: ['Bengaluru', 'Remote'],
    noticePeriodDays: 45,
    skills: ['Figma', 'UI/UX', 'Design Systems', 'User Research'],
    industry: 'Design',
    employmentType: 'Full-time',
    companyType: 'Startup',
    workMode: 'Hybrid',
    education: [{ degree: 'B.Des, Communication Design', institute: 'Srishti Manipal', year: 2021 }],
    workHistory: [{ role: 'Product Designer', company: 'Formless Studio', startYear: 2021, endYear: null }],
    projects: [{ name: 'Onboarding redesign', description: 'Cut sign-up drop-off by 22% with a redesigned onboarding flow and a new design system.' }],
    resumeAvailable: true,
    hasPortfolio: true,
    portfolioLink: 'ananyaiyer.design',
    lastActiveDaysAgo: 6,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: true, profileRecentlyUpdatedDays: 3 },
  },
  {
    id: 'tl-7',
    name: 'Vikram Desai',
    initials: 'VD',
    designation: 'DevOps Engineer',
    currentCompany: 'Cloudframe',
    experienceYears: 5,
    currentSalaryLPA: 22,
    expectedSalaryLPA: 28,
    location: 'Pune',
    preferredLocations: ['Pune', 'Remote'],
    noticePeriodDays: 60,
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Python'],
    industry: 'Technology',
    employmentType: 'Full-time',
    companyType: 'Product',
    workMode: 'Remote',
    education: [{ degree: 'B.Tech, Electronics', institute: 'COEP Pune', year: 2018 }],
    workHistory: [
      { role: 'DevOps Engineer', company: 'Cloudframe', startYear: 2021, endYear: null },
      { role: 'Systems Engineer', company: 'Nimbus IT', startYear: 2018, endYear: 2021 },
    ],
    projects: [{ name: 'Multi-region failover', description: 'Terraform-driven multi-region AWS failover, cutting downtime incidents by 80%.' }],
    resumeAvailable: true,
    hasPortfolio: false,
    portfolioLink: null,
    lastActiveDaysAgo: 14,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: true, profileRecentlyUpdatedDays: 25 },
  },
  {
    id: 'tl-8',
    name: 'Divya Shah',
    initials: 'DS',
    designation: 'QA Engineer',
    currentCompany: 'Meridian Software',
    experienceYears: 3,
    currentSalaryLPA: 10,
    expectedSalaryLPA: 14,
    location: 'Ahmedabad',
    preferredLocations: ['Ahmedabad', 'Remote'],
    noticePeriodDays: 15,
    skills: ['Selenium', 'Cypress', 'API Testing', 'Python'],
    industry: 'Technology',
    employmentType: 'Full-time',
    companyType: 'Services',
    workMode: 'Hybrid',
    education: [{ degree: 'B.E, Information Technology', institute: 'Nirma University', year: 2020 }],
    workHistory: [{ role: 'QA Engineer', company: 'Meridian Software', startYear: 2020, endYear: null }],
    projects: [{ name: 'Regression suite overhaul', description: 'Migrated a 400-case manual suite to Cypress, cutting release regression time by 70%.' }],
    resumeAvailable: true,
    hasPortfolio: false,
    portfolioLink: null,
    lastActiveDaysAgo: 4,
    verification: { phoneVerified: true, emailVerified: false, resumeSubmitted: true, educationVerified: true, employmentVerified: false, profileRecentlyUpdatedDays: 8 },
  },
  {
    id: 'tl-9',
    name: 'Farhan Ali',
    initials: 'FA',
    designation: 'Machine Learning Engineer',
    currentCompany: 'Insight Analytics',
    experienceYears: 3.5,
    currentSalaryLPA: 20,
    expectedSalaryLPA: 27,
    location: 'Hyderabad',
    preferredLocations: ['Hyderabad', 'Bengaluru', 'Remote'],
    noticePeriodDays: 30,
    skills: ['Python', 'PyTorch', 'AWS', 'MLOps', 'SQL'],
    industry: 'Technology',
    employmentType: 'Full-time',
    companyType: 'Product',
    workMode: 'Hybrid',
    education: [{ degree: 'M.Tech, AI & Data Science', institute: 'IIIT Hyderabad', year: 2021 }],
    workHistory: [{ role: 'Machine Learning Engineer', company: 'Insight Analytics', startYear: 2021, endYear: null }],
    projects: [{ name: 'Churn prediction model', description: 'Deployed a PyTorch churn model on AWS SageMaker, now serving 3 product lines.' }],
    resumeAvailable: true,
    hasPortfolio: true,
    portfolioLink: 'github.com/farhanali',
    lastActiveDaysAgo: 11,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: true, profileRecentlyUpdatedDays: 15 },
  },
  {
    id: 'tl-10',
    name: 'Neha Bhatt',
    initials: 'NB',
    designation: 'Sales Manager',
    currentCompany: 'Northwind SaaS',
    experienceYears: 6,
    currentSalaryLPA: 16,
    expectedSalaryLPA: 21,
    location: 'Mumbai',
    preferredLocations: ['Mumbai', 'Remote'],
    noticePeriodDays: 60,
    skills: ['B2B Sales', 'SaaS Sales', 'Negotiation', 'CRM', 'Team Leadership'],
    industry: 'SaaS',
    employmentType: 'Full-time',
    companyType: 'Product',
    workMode: 'Hybrid',
    education: [{ degree: 'MBA, Marketing', institute: 'NMIMS Mumbai', year: 2017 }],
    workHistory: [
      { role: 'Sales Manager', company: 'Northwind SaaS', startYear: 2020, endYear: null },
      { role: 'Senior Sales Executive', company: 'Lumen CRM', startYear: 2017, endYear: 2020 },
    ],
    projects: [],
    resumeAvailable: true,
    hasPortfolio: false,
    portfolioLink: null,
    lastActiveDaysAgo: 20,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: true, profileRecentlyUpdatedDays: 40 },
  },
  {
    id: 'tl-11',
    name: 'Aditya Verma',
    initials: 'AV',
    designation: 'Full Stack Developer',
    currentCompany: 'Studenthood',
    experienceYears: 1.5,
    currentSalaryLPA: 7,
    expectedSalaryLPA: 10,
    location: 'Delhi NCR',
    preferredLocations: ['Delhi NCR', 'Remote'],
    noticePeriodDays: 30,
    skills: ['React', 'Node.js', 'Python', 'MongoDB'],
    industry: 'EdTech',
    employmentType: 'Full-time',
    companyType: 'Startup',
    workMode: 'Remote',
    education: [{ degree: 'B.Tech, Computer Science', institute: 'DTU Delhi', year: 2023 }],
    workHistory: [{ role: 'Full Stack Developer', company: 'Studenthood', startYear: 2023, endYear: null }],
    projects: [{ name: 'Campus placement portal', description: 'MERN-stack portal used by 30 campuses for placement drives.' }],
    resumeAvailable: true,
    hasPortfolio: true,
    portfolioLink: 'github.com/adityaverma',
    lastActiveDaysAgo: 1,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: false, employmentVerified: false, profileRecentlyUpdatedDays: 2 },
  },
  {
    id: 'tl-12',
    name: 'Meera Krishnan',
    initials: 'MK',
    designation: 'Cybersecurity Analyst',
    currentCompany: 'SecureNet Labs',
    experienceYears: 4,
    currentSalaryLPA: 15,
    expectedSalaryLPA: 20,
    location: 'Hyderabad',
    preferredLocations: ['Hyderabad', 'Remote'],
    noticePeriodDays: 45,
    skills: ['Linux', 'SIEM', 'Security', 'Python', 'AWS'],
    industry: 'Technology',
    employmentType: 'Full-time',
    companyType: 'Services',
    workMode: 'Hybrid',
    education: [{ degree: 'B.Tech, Computer Science', institute: 'JNTU Hyderabad', year: 2020 }],
    workHistory: [{ role: 'Cybersecurity Analyst', company: 'SecureNet Labs', startYear: 2020, endYear: null }],
    projects: [{ name: 'SOC automation', description: 'Automated SIEM triage rules that cut analyst response time in half.' }],
    resumeAvailable: true,
    hasPortfolio: false,
    portfolioLink: null,
    lastActiveDaysAgo: 7,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: false, profileRecentlyUpdatedDays: 10 },
  },
  {
    id: 'tl-13',
    name: 'Ishaan Kapoor',
    initials: 'IK',
    designation: 'Backend Developer',
    currentCompany: 'PayEdge',
    experienceYears: 2.8,
    currentSalaryLPA: 13,
    expectedSalaryLPA: 18,
    location: 'Bengaluru',
    preferredLocations: ['Bengaluru'],
    noticePeriodDays: 10,
    skills: ['Python', 'Django', 'AWS', 'FastAPI', 'PostgreSQL'],
    industry: 'Fintech',
    employmentType: 'Full-time',
    companyType: 'Startup',
    workMode: 'On-site',
    education: [{ degree: 'B.E, Computer Science', institute: 'MS Ramaiah Institute', year: 2021 }],
    workHistory: [{ role: 'Backend Developer', company: 'PayEdge', startYear: 2021, endYear: null }],
    projects: [{ name: 'Payments gateway retries', description: 'Rebuilt the retry/idempotency layer for the payments gateway on FastAPI + AWS.' }],
    resumeAvailable: true,
    hasPortfolio: true,
    portfolioLink: 'github.com/ishaank',
    lastActiveDaysAgo: 0,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: true, profileRecentlyUpdatedDays: 0 },
  },
  {
    id: 'tl-14',
    name: 'Ritika Ghosh',
    initials: 'RG',
    designation: 'Marketing Specialist',
    currentCompany: 'Bloomtrail',
    experienceYears: 3,
    currentSalaryLPA: 9,
    expectedSalaryLPA: 12,
    location: 'Kolkata',
    preferredLocations: ['Kolkata', 'Remote'],
    noticePeriodDays: 30,
    skills: ['SEO', 'Content Strategy', 'Analytics', 'Paid Ads'],
    industry: 'E-commerce',
    employmentType: 'Full-time',
    companyType: 'Startup',
    workMode: 'Remote',
    education: [{ degree: 'MBA, Marketing', institute: 'IISWBM Kolkata', year: 2021 }],
    workHistory: [{ role: 'Marketing Specialist', company: 'Bloomtrail', startYear: 2021, endYear: null }],
    projects: [],
    resumeAvailable: true,
    hasPortfolio: false,
    portfolioLink: null,
    lastActiveDaysAgo: 16,
    verification: { phoneVerified: true, emailVerified: true, resumeSubmitted: true, educationVerified: true, employmentVerified: false, profileRecentlyUpdatedDays: 28 },
  },
]

export const KNOWN_SKILLS = [...new Set(TALENT_POOL.flatMap((c) => c.skills))].sort()
export const KNOWN_LOCATIONS = [...new Set(TALENT_POOL.flatMap((c) => [c.location, ...c.preferredLocations]))].filter((l) => l !== 'Remote').sort()
export const KNOWN_INDUSTRIES = [...new Set(TALENT_POOL.map((c) => c.industry))].sort()
export const KNOWN_DESIGNATIONS = [...new Set(TALENT_POOL.map((c) => c.designation))].sort()
